In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104, 105],
    'Name': ['Asha', 'Rahul', 'Priya', 'Kiran', 'Sneha'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Sales']
})

salaries = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 106],
    'Salary': [50000, 40000, 45000, 60000]
})

display(employees)
display(salaries)

   Emp_ID   Name Department
0     101   Asha         IT
1     102  Rahul         HR
2     103  Priya      Sales
3     104  Kiran         IT
4     105  Sneha      Sales

   Emp_ID  Salary
0     101   50000
1     102   40000
2     103   45000
3     106   60000

In [3]:
inner_merge = pd.merge(employees, salaries, on='Emp_ID', how='inner')
display(inner_merge)

   Emp_ID   Name Department  Salary
0     101   Asha         IT   50000
1     102  Rahul         HR   40000
2     103  Priya      Sales   45000

In [4]:
left_merge = pd.merge(employees, salaries, on='Emp_ID', how='left')
display(left_merge)

   Emp_ID   Name Department   Salary
0     101   Asha         IT  50000.0
1     102  Rahul         HR  40000.0
2     103  Priya      Sales  45000.0
3     104  Kiran         IT      NaN
4     105  Sneha      Sales      NaN

In [5]:
right_merge = pd.merge(employees, salaries, on='Emp_ID', how='right')
display(right_merge)

   Emp_ID   Name Department  Salary
0     101   Asha         IT   50000
1     102  Rahul         HR   40000
2     103  Priya      Sales   45000
3     106    NaN        NaN   60000

In [6]:
outer_merge = pd.merge(employees, salaries, on='Emp_ID', how='outer')
display(outer_merge)

   Emp_ID   Name Department   Salary
0     101   Asha         IT  50000.0
1     102  Rahul         HR  40000.0
2     103  Priya      Sales  45000.0
3     104  Kiran         IT      NaN
4     105  Sneha      Sales      NaN
5     106    NaN        NaN  60000.0

In [7]:
df1 = pd.DataFrame({
    'Name': ['Asha', 'Rahul'],
    'Age': [22, 23]
})

df2 = pd.DataFrame({
    'Name': ['Priya', 'Kiran'],
    'Age': [21, 24]
})

combined = pd.concat([df1, df2], ignore_index=True)

display(combined)

    Name  Age
0   Asha   22
1  Rahul   23
2  Priya   21
3  Kiran   24

In [8]:
sales = pd.DataFrame({
    'Region': ['South', 'South', 'North', 'North', 'East', 'East'],
    'Product': ['Laptop', 'Mobile', 'Laptop', 'Mobile', 'Laptop', 'Mobile'],
    'Sales': [50000, 30000, 60000, 25000, 45000, 35000]
})

display(sales)

  Region Product  Sales
0  South  Laptop  50000
1  South  Mobile  30000
2  North  Laptop  60000
3  North  Mobile  25000
4   East  Laptop  45000
5   East  Mobile  35000

In [9]:
pivot = pd.pivot_table(
    sales,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum'
)

display(pivot)

Product  Laptop  Mobile
Region
East      45000   35000
North     60000   25000
South     50000   30000

In [10]:
wide_data = pd.DataFrame({
    'Product': ['Laptop', 'Mobile', 'Tablet'],
    'January': [50000, 30000, 20000],
    'February': [55000, 35000, 25000],
    'March': [60000, 40000, 30000]
})

long_data = pd.melt(
    wide_data,
    id_vars=['Product'],
    var_name='Month',
    value_name='Sales'
)

display(long_data)

  Product     Month  Sales
0  Laptop   January  50000
1  Mobile   January  30000
2  Tablet   January  20000
3  Laptop  February  55000
4  Mobile  February  35000
5  Tablet  February  25000
6  Laptop     March  60000
7  Mobile     March  40000
8  Tablet     March  30000

In [11]:
result = (
    sales
    .groupby('Region')['Sales']
    .sum()
    .reset_index()
    .sort_values(by='Sales', ascending=False)
)

display(result)

  Region  Sales
1  North  85000
0   East  80000
2  South  80000

In [12]:
print("Total Sales:", sales['Sales'].sum())

print("\nAverage Sales:", sales['Sales'].mean())

print("\nSales by Region:")
display(sales.groupby('Region')['Sales'].sum())

print("\nHighest Sales:")
display(sales.loc[[sales['Sales'].idxmax()]])

Total Sales: 245000

Average Sales: 40833.333333333336

Sales by Region:

Region
East     80000
North    85000
South    80000
Name: Sales, dtype: int64

Highest Sales:

  Region Product  Sales
2  North  Laptop  60000