In [1]:
import pandas as pd

In [2]:
data = {
    "Product": ["Laptop", "Phone", "Laptop", "Headphones", "Phone", "Laptop"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Accessories", "Electronics", "Electronics"],
    "Region": ["South", "North", "South", "West", "North", "East"],
    "Sales": [50000, 20000, 55000, 3000, 25000, 48000],
    "Quantity": [2, 3, 2, 5, 4, 1]
}

df = pd.DataFrame(data)

df

      Product     Category Region  Sales  Quantity
0      Laptop  Electronics  South  50000         2
1       Phone  Electronics  North  20000         3
2      Laptop  Electronics  South  55000         2
3  Headphones  Accessories   West   3000         5
4       Phone  Electronics  North  25000         4
5      Laptop  Electronics   East  48000         1

In [3]:
df.head()

      Product     Category Region  Sales  Quantity
0      Laptop  Electronics  South  50000         2
1       Phone  Electronics  North  20000         3
2      Laptop  Electronics  South  55000         2
3  Headphones  Accessories   West   3000         5
4       Phone  Electronics  North  25000         4

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   6 non-null      str
 1   Category  6 non-null      str
 2   Region    6 non-null      str
 3   Sales     6 non-null      int64
 4   Quantity  6 non-null      int64
dtypes: int64(2), str(3)
memory usage: 372.0 bytes

In [5]:
df.describe()

             Sales  Quantity
count      6.00000  6.000000
mean   33500.00000  2.833333
std    20637.34479  1.471960
min     3000.00000  1.000000
25%    21250.00000  2.000000
50%    36500.00000  2.500000
75%    49500.00000  3.750000
max    55000.00000  5.000000

In [6]:
df["Product"].value_counts()

Product
Laptop        3
Phone         2
Headphones    1
Name: count, dtype: int64

In [7]:
df[["Product", "Sales"]]

      Product  Sales
0      Laptop  50000
1       Phone  20000
2      Laptop  55000
3  Headphones   3000
4       Phone  25000
5      Laptop  48000

In [8]:
df[df["Sales"] > 30000]

  Product     Category Region  Sales  Quantity
0  Laptop  Electronics  South  50000         2
2  Laptop  Electronics  South  55000         2
5  Laptop  Electronics   East  48000         1

In [9]:
df.isnull().sum()

Product     0
Category    0
Region      0
Sales       0
Quantity    0
dtype: int64

In [10]:
df_clean = df.copy()

df_clean.loc[0, "Sales"] = None

df_clean.isnull().sum()

Product     0
Category    0
Region      0
Sales       1
Quantity    0
dtype: int64

In [11]:
df_clean["Sales"] = df_clean["Sales"].fillna(
    df_clean["Sales"].mean()
)

df_clean.isnull().sum()

Product     0
Category    0
Region      0
Sales       0
Quantity    0
dtype: int64

In [12]:
df.groupby("Region")["Sales"].sum()

Region
East      48000
North     45000
South    105000
West       3000
Name: Sales, dtype: int64

In [13]:
df.groupby("Category").agg(
    total_sales=("Sales", "sum"),
    average_sales=("Sales", "mean"),
    total_quantity=("Quantity", "sum")
)

             total_sales  average_sales  total_quantity
Category
Accessories         3000         3000.0               5
Electronics       198000        39600.0              12

In [14]:
df_clean.to_csv("cleaned_sales.csv", index=False)