In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Asha', 'Rahul', 'Priya', 'Kiran', 'Sneha', 'Arjun', 'Meena', 'Ravi', 'Anita', 'John'],
    'Department': ['IT', 'hr', 'Sales', 'IT ', 'sales', 'HR', 'IT', ' sales ', 'HR', 'IT'],
    'Age': [25, 30, np.nan, 28, 150, 32, 27, 29, 26, 31],
    'Salary': [50000, 45000, 60000, np.nan, 55000, 48000, 52000, 51000, 47000, 50000],
    'Experience': [2, 5, 3, 4, 6, np.nan, 2, 3, 4, 5]
}

df = pd.DataFrame(data)

# Add a duplicate record
df = pd.concat([df, df.iloc[[0]]], ignore_index=True)

display(df)

    Employee_ID   Name Department    Age   Salary  Experience
0           101   Asha         IT   25.0  50000.0         2.0
1           102  Rahul         hr   30.0  45000.0         5.0
2           103  Priya      Sales    NaN  60000.0         3.0
3           104  Kiran        IT    28.0      NaN         4.0
4           105  Sneha      sales  150.0  55000.0         6.0
5           106  Arjun         HR   32.0  48000.0         NaN
6           107  Meena         IT   27.0  52000.0         2.0
7           108   Ravi     sales    29.0  51000.0         3.0
8           109  Anita         HR   26.0  47000.0         4.0
9           110   John         IT   31.0  50000.0         5.0
10          101   Asha         IT   25.0  50000.0         2.0

In [3]:
print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (11, 6)

Missing Values:
Employee_ID    0
Name           0
Department     0
Age            1
Salary         1
Experience     1
dtype: int64

Duplicate Records:
1

Data Types:
Employee_ID      int64
Name            object
Department      object
Age            float64
Salary         float64
Experience     float64
dtype: object

In [4]:
print(df.isnull().sum())

Employee_ID    0
Name           0
Department     0
Age            1
Salary         1
Experience     1
dtype: int64

In [5]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [6]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [7]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [9]:
df['Experience'] = df['Experience'].ffill()

In [10]:
print(df.isnull().sum())

Employee_ID    0
Name           0
Department     0
Age            0
Salary         0
Experience     0
dtype: int64

In [11]:
print("Duplicates Before Cleaning:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates After Cleaning:", df.duplicated().sum())

Duplicates Before Cleaning: 1
Duplicates After Cleaning: 0

In [12]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

outliers = df[(df['Age'] < lower_limit) | (df['Age'] > upper_limit)]

print("Outliers:")
display(outliers)

Lower Limit: 20.5
Upper Limit: 38.5
Outliers:

   Employee_ID   Name Department    Age   Salary  Experience
2          103  Priya      Sales   40.3  60000.0         3.0
4          105  Sneha      sales  150.0  55000.0         6.0

In [13]:
df['Age'] = df['Age'].clip(lower=lower_limit, upper=upper_limit)

print("Outliers Capped Successfully")

Outliers Capped Successfully

In [14]:
df['Department'] = df['Department'].str.strip().str.title()

df['Name'] = df['Name'].str.strip().str.title()

display(df)

   Employee_ID   Name Department   Age   Salary  Experience
0          101   Asha         It  25.0  50000.0         2.0
1          102  Rahul         Hr  30.0  45000.0         5.0
2          103  Priya      Sales  38.5  60000.0         3.0
3          104  Kiran         It  28.0  50000.0         4.0
4          105  Sneha      Sales  38.5  55000.0         6.0
5          106  Arjun         Hr  32.0  48000.0         6.0
6          107  Meena         It  27.0  52000.0         2.0
7          108   Ravi      Sales  29.0  51000.0         3.0
8          109  Anita         Hr  26.0  47000.0         4.0
9          110   John         It  31.0  50000.0         5.0

In [15]:
comparison = pd.DataFrame({
    'Metric': ['Total Rows', 'Missing Values', 'Duplicate Rows'],
    'Before Cleaning': [11, 3, 1],
    'After Cleaning': [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

display(comparison)

           Metric  Before Cleaning  After Cleaning
0      Total Rows               11              10
1  Missing Values                3               0
2  Duplicate Rows                1               0

In [16]:
print("Final Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

display(df.head(10))

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     int64
 1   Name         10 non-null     object
 2   Department   10 non-null     object
 3   Age          10 non-null     float64
 4   Salary       10 non-null     float64
 5   Experience   10 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 560.0+ bytes

Missing Values:
Employee_ID    0
Name           0
Department     0
Age            0
Salary         0
Experience     0
dtype: int64

Duplicate Records:
0

   Employee_ID   Name Department   Age   Salary  Experience
0          101   Asha         It  25.0  50000.0         2.0
1          102  Rahul         Hr  30.0  45000.0         5.0
2          103  Priya      Sales  38.5  60000.0         3.0
3          104  Kiran         It  28.0  50000.0         4.0
4          105  Sneha      Sales  38.5  55000.0         6.0
5          106  Arjun         Hr  32.0  48000.0         6.0
6          107  Meena         It  27.0  52000.0         2.0
7          108   Ravi      Sales  29.0  51000.0         3.0
8          109  Anita         Hr  26.0  47000.0         4.0
9          110   John         It  31.0  50000.0         5.0

In [17]:
df.to_csv('cleaned_dataset.csv', index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!